/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import audio.AePlayWave;
import audio.PlayAudio;
import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Paola Guadalupe Gutierrez Santana
 */
public class JuegoGato extends javax.swing.JFrame {
    
int turno;

    /**
     * Creates new form JuegoGato
     */
    public JuegoGato() {
        initComponents();
        int turno = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtJugador1 = new javax.swing.JTextField();
        Jugador1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJugador2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BotonCelda1 = new javax.swing.JButton();
        BotonCelda2 = new javax.swing.JButton();
        BotonCelda3 = new javax.swing.JButton();
        BotonCelda4 = new javax.swing.JButton();
        BotonCelda5 = new javax.swing.JButton();
        BotonCelda6 = new javax.swing.JButton();
        BotonCelda7 = new javax.swing.JButton();
        BotonCelda8 = new javax.swing.JButton();
        BotonCelda9 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        botonJugar = new javax.swing.JButton();
        botonVolverJugar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("DK Crayon Crumble", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tumblr_mfk1zmFux31s1pf5po1_500.png"))); // NOI18N
        jLabel1.setText("Juego del Gato");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        txtJugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJugador1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJugador1MouseExited(evt);
            }
        });

        Jugador1.setBackground(new java.awt.Color(204, 204, 255));
        Jugador1.setFont(new java.awt.Font("Luna", 0, 24)); // NOI18N
        Jugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png"))); // NOI18N
        Jugador1.setText("Jugador 1");
        Jugador1.setOpaque(true);
        Jugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jugador1MouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Luna", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png"))); // NOI18N
        jLabel3.setText("Jugador 2");

        txtJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJugador1)
                            .addComponent(txtJugador2))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setForeground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new java.awt.GridLayout(3, 3));

        BotonCelda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda1.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda1.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda1.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda1ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda1);

        BotonCelda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda2.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda2.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda2.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda2ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda2);

        BotonCelda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda3.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda3.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda3.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda3ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda3);

        BotonCelda4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda4.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda4.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda4.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda4ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda4);

        BotonCelda5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda5.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda5.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda5.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda5ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda5);

        BotonCelda6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda6.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda6.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda6.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda6ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda6);

        BotonCelda7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda7.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda7.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda7.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda7ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda7);

        BotonCelda8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda8.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda8.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda8.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda8ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda8);

        BotonCelda9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif"))); // NOI18N
        BotonCelda9.setMaximumSize(new java.awt.Dimension(100, 150));
        BotonCelda9.setMinimumSize(new java.awt.Dimension(100, 150));
        BotonCelda9.setPreferredSize(new java.awt.Dimension(100, 150));
        BotonCelda9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCelda9ActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCelda9);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        botonJugar.setBackground(new java.awt.Color(204, 204, 255));
        botonJugar.setFont(new java.awt.Font("DK Crayon Crumble", 0, 36)); // NOI18N
        botonJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen1.png"))); // NOI18N
        botonJugar.setText("Jugar");
        botonJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonJugarMouseExited(evt);
            }
        });
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });
        jPanel6.add(botonJugar);

        botonVolverJugar.setBackground(new java.awt.Color(204, 204, 255));
        botonVolverJugar.setFont(new java.awt.Font("DK Crayon Crumble", 0, 36)); // NOI18N
        botonVolverJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen1.png"))); // NOI18N
        botonVolverJugar.setText("Volver a jugar");
        botonVolverJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonVolverJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVolverJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVolverJugarMouseExited(evt);
            }
        });
        botonVolverJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverJugarActionPerformed(evt);
            }
        });
        jPanel6.add(botonVolverJugar);

        botonSalir.setBackground(new java.awt.Color(204, 204, 255));
        botonSalir.setFont(new java.awt.Font("DK Crayon Crumble", 0, 36)); // NOI18N
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagen1.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel6.add(botonSalir);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Ganador(){
        
        //ganador 0
        if (BotonCelda1.getActionCommand() == "0" && BotonCelda2.getActionCommand() == "0" && BotonCelda3.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        if (BotonCelda4.getActionCommand() == "0" && BotonCelda5.getActionCommand() == "0" && BotonCelda6.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        if (BotonCelda7.getActionCommand() == "0" && BotonCelda8.getActionCommand() == "0" && BotonCelda9.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        if (BotonCelda1.getActionCommand() == "0" && BotonCelda4.getActionCommand() == "0" && BotonCelda7.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        if (BotonCelda2.getActionCommand() == "0" && BotonCelda5.getActionCommand() == "0" && BotonCelda8.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        if (BotonCelda3.getActionCommand() == "0" && BotonCelda6.getActionCommand() == "0" && BotonCelda9.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        if (BotonCelda1.getActionCommand() == "0" && BotonCelda2.getActionCommand() == "0" && BotonCelda3.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        if (BotonCelda1.getActionCommand() == "0" && BotonCelda5.getActionCommand() == "0" && BotonCelda9.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        if (BotonCelda3.getActionCommand() == "0" && BotonCelda5.getActionCommand() == "0" && BotonCelda7.getActionCommand() == "0"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador1.getText()); 
        }
        
        //ganador 1
        
        if (BotonCelda1.getActionCommand() == "1" && BotonCelda2.getActionCommand() == "1" && BotonCelda3.getActionCommand() == "1"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador2.getText()); 
        }
        
        if (BotonCelda4.getActionCommand() == "1" && BotonCelda5.getActionCommand() == "1" && BotonCelda6.getActionCommand() == "1"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador2.getText()); 
        }
        
        if (BotonCelda7.getActionCommand() == "1" && BotonCelda8.getActionCommand() == "1" && BotonCelda9.getActionCommand() == "1"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador2.getText()); 
        }
        
        if (BotonCelda1.getActionCommand() == "1" && BotonCelda4.getActionCommand() == "1" && BotonCelda7.getActionCommand() == "1"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador2.getText()); 
        }
        
        if (BotonCelda2.getActionCommand() == "1" && BotonCelda5.getActionCommand() == "1" && BotonCelda8.getActionCommand() == "1"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador2.getText()); 
        }
        
        if (BotonCelda3.getActionCommand() == "1" && BotonCelda6.getActionCommand() == "1" && BotonCelda9.getActionCommand() == "1"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador2.getText()); 
        }
        
        if (BotonCelda1.getActionCommand() == "1" && BotonCelda5.getActionCommand() == "1" && BotonCelda9.getActionCommand() == "1"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador2.getText()); 
        }
        
        if (BotonCelda3.getActionCommand() == "1" && BotonCelda5.getActionCommand() == "1" && BotonCelda7.getActionCommand() == "1"){
            JOptionPane.showMessageDialog(null, " Ganador " + txtJugador2.getText()); 
        }
    
}
    
    
//limpiar para volver a jugar
    private void VolverJugar(){
        if (turno == 0) {
            BotonCelda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda1.setActionCommand("");
        }else{
            BotonCelda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda1.setActionCommand("");
            turno = 0;
        }
        
        if (turno == 0) {
            BotonCelda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda2.setActionCommand("");
            turno = 1;
        }else{
            BotonCelda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda2.setActionCommand("");
            turno = 0;
        }
        
        if (turno == 0) {
            BotonCelda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda3.setActionCommand("");
            turno = 1;
        }else{
            BotonCelda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda3.setActionCommand("");
            turno = 0;
        }
        
        if (turno == 0) {
            BotonCelda4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda4.setActionCommand("");
            turno = 1;
        }else{
            BotonCelda4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda4.setActionCommand("");
            turno = 0;
        }
        
        if (turno == 0) {
            BotonCelda5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda5.setActionCommand("");
            turno = 1;
        }else{
            BotonCelda5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda5.setActionCommand("");
            turno = 0;
        }
        
        if (turno == 0) {
            BotonCelda6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda6.setActionCommand("");
            turno = 1;
        }else{
            BotonCelda6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda6.setActionCommand("");
            turno = 0;
        }
        
        if (turno == 0) {
            BotonCelda7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda7.setActionCommand("");
            turno = 1;
        }else{
            BotonCelda7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda7.setActionCommand("");
            turno = 0;
        }
        
        if (turno == 0) {
            BotonCelda8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda8.setActionCommand("");
            turno = 1;
        }else{
            BotonCelda8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda8.setActionCommand("");
            turno = 0;
        }
        
        if (turno == 0) {
            BotonCelda9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda9.setActionCommand("");
            turno = 1;
        }else{
            BotonCelda9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200_s.gif")));
            BotonCelda9.setActionCommand("");
            turno = 0;
        }
        
        txtJugador1.setText("");
        txtJugador2.setText("");
    }
    
    
    
    
    private void Jugador1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jugador1MouseEntered
        // TODO add your handling code here:        
    }//GEN-LAST:event_Jugador1MouseEntered

    private void BotonCelda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda1ActionPerformed
        // TODO add your handling code here:
       //poner audio al boton
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       //cambiar la imagen 
        if (BotonCelda1.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda1.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda1.setActionCommand("1");
                turno = 0;
                this.Ganador();
                        
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
        
    }//GEN-LAST:event_BotonCelda1ActionPerformed

    private void BotonCelda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda2ActionPerformed
        // TODO add your handling code here:
        //poner sonido    
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //cambiar la imagen 
        if (BotonCelda2.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda2.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda2.setActionCommand("1");
                turno = 0;
                this.Ganador();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
    
    }//GEN-LAST:event_BotonCelda2ActionPerformed

    private void BotonCelda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda3ActionPerformed
        // TODO add your handling code here:
       //poner sonido    
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         //cambiar la imagen 
        if (BotonCelda3.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda3.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda3.setActionCommand("1");
                turno = 0;
                this.Ganador();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
    
        
    }//GEN-LAST:event_BotonCelda3ActionPerformed

    private void BotonCelda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda4ActionPerformed
        // TODO add your handling code here:
         //poner sonido 
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         //cambiar la imagen 
        if (BotonCelda4.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda4.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda4.setActionCommand("1");
                turno = 0;
                this.Ganador();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
    
    }//GEN-LAST:event_BotonCelda4ActionPerformed

    private void BotonCelda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda5ActionPerformed
        // TODO add your handling code here:
        //poner sonido 
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         //cambiar la imagen 
        if (BotonCelda5.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda5.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda5.setActionCommand("1");
                turno = 0;
                this.Ganador();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
    }//GEN-LAST:event_BotonCelda5ActionPerformed

    private void BotonCelda6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda6ActionPerformed
        // TODO add your handling code here:
        //poner sonido
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         //cambiar la imagen 
        if (BotonCelda6.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda6.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda6.setActionCommand("1");
                turno = 0;
                this.Ganador();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
    }//GEN-LAST:event_BotonCelda6ActionPerformed

    private void BotonCelda7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda7ActionPerformed
        // TODO add your handling code here:
        //poner sonido
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         //cambiar la imagen 
        if (BotonCelda7.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda7.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda7.setActionCommand("1");
                turno = 0;
                this.Ganador();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
    }//GEN-LAST:event_BotonCelda7ActionPerformed

    private void BotonCelda8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda8ActionPerformed
        // TODO add your handling code here:
        //poner sonido 
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         //cambiar la imagen 
        if (BotonCelda8.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda8.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda8.setActionCommand("1");
                turno = 0;
                this.Ganador();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
    }//GEN-LAST:event_BotonCelda8ActionPerformed

    private void BotonCelda9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCelda9ActionPerformed
        // TODO add your handling code here:
        //poner sonido
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         //cambiar la imagen 
        if (BotonCelda9.getActionCommand().isEmpty()){
            if(turno == 0) {
                BotonCelda9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                BotonCelda9.setActionCommand("0");
                turno = 1;
                this.Ganador();
                
            }else{
                BotonCelda9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
                BotonCelda9.setActionCommand("1");
                turno = 0;
                this.Ganador();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Esta casilla esta ocupada");
        }
    }//GEN-LAST:event_BotonCelda9ActionPerformed

    private void txtJugador1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJugador1MouseEntered

    private void txtJugador1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador1MouseExited
        // TODO add your handling code here:        
    }//GEN-LAST:event_txtJugador1MouseExited

    private void botonVolverJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverJugarActionPerformed
        // TODO add your handling code here:
        this.VolverJugar();
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/jump.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_botonVolverJugarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/jump.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null,"Fin del juego");
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/jump.wav");
            aw = new AePlayWave(url);
            aw.start();
            
            String j1 = JOptionPane.showInputDialog("Ingresa el nombre del Jugador 1");
            txtJugador1.setText(j1); 
            
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/jump.wav");
            aw = new AePlayWave(url);
            aw.start();
            
            String j2 = JOptionPane.showInputDialog("Ingresa el nombre del Jugador 2");
            txtJugador2.setText(j2); 
            
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_botonJugarActionPerformed

    private void txtJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugador2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtJugador2ActionPerformed

    private void botonJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMouseEntered
        // TODO add your handling code here:
        botonJugar.setBackground(new java.awt.Color(255,255,204));
    }//GEN-LAST:event_botonJugarMouseEntered

    private void botonJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonJugarMouseExited
        // TODO add your handling code here:
        botonJugar.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_botonJugarMouseExited

    private void botonVolverJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverJugarMouseEntered
        // TODO add your handling code here:
        botonVolverJugar.setBackground(new java.awt.Color(255,255,204));
    }//GEN-LAST:event_botonVolverJugarMouseEntered

    private void botonVolverJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverJugarMouseExited
        // TODO add your handling code here:
        botonVolverJugar.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_botonVolverJugarMouseExited

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        // TODO add your handling code here:
        botonSalir.setBackground(new java.awt.Color(255,255,204));
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        // TODO add your handling code here:
        botonSalir.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_botonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoGato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCelda1;
    private javax.swing.JButton BotonCelda2;
    private javax.swing.JButton BotonCelda3;
    private javax.swing.JButton BotonCelda4;
    private javax.swing.JButton BotonCelda5;
    private javax.swing.JButton BotonCelda6;
    private javax.swing.JButton BotonCelda7;
    private javax.swing.JButton BotonCelda8;
    private javax.swing.JButton BotonCelda9;
    private javax.swing.JLabel Jugador1;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVolverJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}

